server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: user
    password: user

  jpa:
    hibernate:
      ddl-auto: update