server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: user
    password: user

  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: "change-me-dev-change-me-dev-change-me-dev-change-me-dev-123456"
    expirationMinutes: 60